### ISSUE TITLE
Release 0.4.0

### ISSUE THREAD

**Issue by theHacker** [CorantGmbH/aioairq#7] opened 2024-05-04 19:11 UTC
Hi guys,

I was wondering, when you will release the 0.4.0 to PyPI?
Without the changes to `aioairq` released into the wild, I cannot get anything coded into HA's integration. :smile:

**Comment by Sibgatulin** [comment] 2024-05-07 11:01
Hi @theHacker, thanks for the reminder. Does not seem like there is anything stopping from doing it now, I'll get to it later today. 
Do you have objections to [jumping on](https://github.com/CorantGmbH/aioairq/compare/1264a9b1fc9a549d3f8701ad49b142adbcd9ffc0...78c1d3703defd2f868ae60e8ea13e0bd24b9e97a
) to releasing current main head as 0.4.1?

**Comment by Sibgatulin** [comment] 2024-05-07 18:19
My poor engineering and memory come to bite me. [test_dns_caching_by_repeated_calls](https://github.com/CorantGmbH/aioairq/blob/78c1d3703defd2f868ae60e8ea13e0bd24b9e97a/tests/test_access.py#L26) is failing for me at `address=HOSTNAME` and `repeat_call=True`. 
I don't remember if 1. it never worked and was meant to be marked as `xfail`, 2. I misconfigured my system in the meantime, or 3. I introduced a regression somewhere (unlikely, as it seems to fail at earlier releases too, but makes me hesitant to publish to PyPI right now).
@theHacker did you have success running the test with an [FQHN](https://github.com/CorantGmbH/aioairq/issues/2#issuecomment-1877566882)

**Comment by theHacker** [comment] 2024-05-08 17:30
Guys :angry: … The test suite does not run for me anymore, `test_time_server` fails. And this applies to the commit, I made last (`Bump version to 0.4.0`). It worked before.

After debugging into this I found out the reason. air-Q reporting back `""Error: 'TimeServer' is only available for air-Q Science!\\n""`.

That's what I get from upgrading the firmware recently (air-Q LEDs were to bright some day and I could not set them dimmer, so I thought I upgrade the firmware to see if the bug disappears). Will never do so again. Luckily I got the right value set already. Now I must never move this device to a different network and never migrate the time server to a different IP as the value is burnt in forever :see_no_evil: 

**Why the fuck is setting the time a Science-only feature?!! :facepalm:** 
What do I need to do to reset my air-Q to the version before? I now have `1.20.2.r6_D_1.87.0`, I believe one of the numbers was one smaller before I did the upgrade. Not sure, if it was `1.19.something` or `1.86.something`.

I know this does not help with this PR, however, some points I want you to think about:
- I put a lot of money into multiple of these devices.
- I put my spare time into improving your client library. (One could think this is YOUR job, not MINE)
- I still have one of my devices exclusivly non-productive standing around to work on the client library, and so my plan, on the Home Assistant integration (a really nice gesture would have been to provide a device for such purpose).

… and now I have basically a bricked device. Sorry, but I am pissed right now. :anger:

**Comment by dl2080** [comment] 2024-05-14 08:56
> … and now I have basically a bricked device. Sorry, but I am pissed right now. 💢
I am sorry for aggrieving you with our decision to restrict the API a bit.
We will contact you soon and find a solution to honour your time and effort put into client library and Home Assistant integration.

**Comment by Sibgatulin** [comment] 2024-05-14 18:52
1. My question from above regarding the `test_dns_caching_by_repeated_calls` is resolved, it was indeed a misconfiguration on my end, the test works as expected.
2. The state of `aioairq`, that allowed silent failure due to the change of the firmware behaviour was a bug, and is addressed in #8 
3. All of the above has been published to PyPI as `0.4.2`. Thanks for bringing up the topic of publishing the package. I will open a PR to bump the version in HA dependencies.
4. As Daniel mentioned above, your contributions to this client library are genuinely appreciated. I also acknowledge that the features you have been contributing are directly and disruptively affected by recent changes to the API access policy. Yet, as unfortunate as the situation is, it does not qualify as an issue with this client library per se. 
5. In the light of the two points above, I am closing this issue, and some of the points you brought up will be addressed separately and privately. Yet, one other issue I'd like to address here for the record: it is unlikely that a firmware update in question genuinely leaves a device _bricked_, as an air-Q can, at the very least, be reset. However, as said above, for such general or firmware related issues, please, consider the [air-Q forum](https://forum.air-q.com/) instead of this issue tracker.

**Closed by Sibgatulin** 2024-05-14 18:52 UTC

**Comment by mario-airq** [comment] 2024-05-15 13:58
@theHacker I wrote you an e-mail. could you please verify your air-Q serial numbers.
